language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

before_script:
  # TODO: Re-enable after dropping 5.3 support:
  # - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - curl -OL https://github.com/squizlabs/PHP_CodeSniffer/releases/download/2.9.1/phpcs.phar
  - wget https://github.com/Icinga/icingaweb2/archive/v2.4.0.tar.gz
  - tar xfz v2.4.0.tar.gz
  - ln -s icingaweb2-2.4.0/library/Icinga
  - ln -s icingaweb2-2.4.0/library/vendor/Zend

script:
  - php phpcs.phar
  - phpunit --testdox || phpunit --verbose
